name: Build and Deploy - Production
on: 
  workflow_dispatch:
  
jobs:
  slack_update_pending_apr_prod_one:    
    uses: ./.github/workflows/slack_post.yml
    
  deploy-to-prod-one:      
    uses: ./.github/workflows/reusable-deploy-to-server.yml
    with:
      environment: 'PROD'
      
  slack_update_pending_apr_prod_two:    
    needs: [deploy-to-prod-one,slack_update_pending_apr_prod_one]
    uses: ./.github/workflows/slack_update.yml
    with:
      continue-on-error: false
    
  deploy-to-prod-two:
    needs: deploy-to-prod-one
    uses: ./.github/workflows/reusable-deploy-to-server.yml
    with:
      environment: 'PROD'
