name: Build and Deploy - Staging

on:
  workflow_dispatch:
       
jobs:      
  slack_update_in_progress:    
    uses: ./.github/workflows/slack_post.yml   

  deploy-to-staging:      
    uses: ./.github/workflows/reusable-deploy-to-server.yml
    with:
      environment: 'Staging'

  deploy-status-staging:
    runs-on: ubuntu-latest
    needs: deploy-to-staging
    outputs:
      output1: ${{ steps.step1.outputs.staging-result }}
    if: always()
    steps:
      - name: Echo status
        id: step1
        env:
          staging-result: ${{ needs.deploy-to-staging.outputs.result_deploy_server }}
        run: | 
          echo "staging-result=${{ needs.deploy-to-staging.outputs.result_deploy_server }}" >> $GITHUB_OUTPUT
          if [[ staging-result == '' ]]; then
            staging-result= 'failure' >> $GITHUB_OUTPUT
          fi


  # slack_update_result_success_failure:    
  #   needs: [deploy-to-staging, slack_update_in_progress]
  #   if: ${{ always() && success('slack_update_in_progress') }}    
  #   uses: Access-Segment/Sitecore/.github/workflows/slack_result.yml@main
  #   with:
  #     SITE_URL: 'https://staging.jlg.com'
  #     SUCCESS_CHECK: ${{ needs.deploy-status-staging.outputs.output1 == 'success' && 'true' || 'false' }}
  #     FAILURE_CHECK: ${{ needs.deploy-status-staging.outputs.output1 == 'failure' && needs.deploy-to-staging.outputs.reviewed == 'true' && 'true' || 'false' }}
  #     CANCELLED_CHECK: 'false'
  #     WORKFLOW_NAME: ${{ github.workflow }}
