name: Build and Deploy - Production
on: 
  workflow_dispatch:
  
jobs:
  slack_update_pending_apr_prod_one:    
    uses: ./.github/workflows/slack_post.yml
    
  deploy-to-prod-one:      
    uses: ./.github/workflows/reusable-deploy-to-server.yml
    with:
      environment: 'PROD'



      
  slack_update_pending_apr_prod_two:    
    needs: [deploy-to-prod-one,slack_update_pending_apr_prod_one]
    uses: ./.github/workflows/slack_update.yml
    with:
      continue-on-error: true
    
  deploy-to-prod-two:
    needs: deploy-to-prod-one
    uses: ./.github/workflows/reusable-deploy-to-server.yml
    with:
      environment: 'PROD'

  set_success_fail_workflow_name: 
    needs: [slack_update_pending_apr_prod_one, deploy-to-prod-one,slack_update_pending_apr_prod_two, deploy-to-prod-two]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    outputs: 
      slack_workflow_name: ${{ steps.set-slack-workflow-name.outputs.slack_workflow_name }}
      prod_one_result: ${{ steps.set-slack-workflow-name.outputs.prod_one_result }}
      prod_two_result: ${{ steps.set-slack-workflow-name.outputs.prod_two_result }}
    steps:
    - name: Set workflow name for slack message
      id: set-slack-workflow-name
      env:
        prod_one_result: ${{ needs.deploy-to-prod-one.outputs.result_deploy_server }}
        prod_two_result: ${{ needs.deploy-to-prod-two.outputs.result_deploy_server }}
        prod_one_reviewed: ${{ needs.deploy-to-prod-one.outputs.reviewed }}
        prod_two_reviewed: ${{ needs.deploy-to-prod-two.outputs.reviewed }}
      run: |
        if [[ $prod_one_result == 'success' ]]; then
          prod_one_result='success' >> $GITHUB_OUTPUT 
        else
          prod_one_result='failure' >> $GITHUB_OUTPUT
        fi
        
        if [[ $prod_two_result == 'success' ]]; then
          prod_two_result='success' >> $GITHUB_OUTPUT 
        else
           prod_two_result='failure' >> $GITHUB_OUTPUT 
        fi

        
        echo $prod_one_result
        echo $prod_two_result
        echo $prod_one_reviewed
        echo $prod_two_reviewed
        
        if [[ $prod_one_result == 'cancelled' ]]; then            
           echo "slack_workflow_name=Build and Deploy - Prod1" >> $GITHUB_OUTPUT   
        elif [[ $prod_two_result == 'cancelled' ]]; then            
          echo "slack_workflow_name=Build and Deploy - Prod2" >> $GITHUB_OUTPUT                    
        elif [[ $prod_one_result == 'failure' ]] && [[ $prod_one_reviewed == 'true' ]]; then              
           echo "slack_workflow_name=Build and Deploy - Prod1" >> $GITHUB_OUTPUT                    
        elif [[ $prod_one_result == 'failure' ]] && [[ $prod_one_reviewed != 'true' ]]; then                  
           echo "slack_workflow_name=Build and Deploy - Prod1" >> $GITHUB_OUTPUT                                       
        elif [[ $prod_one_result == 'success' ]] && [[ $prod_two_result == 'success' ]]; then                         
           echo "slack_workflow_name=Build and Deploy - Prod2" >> $GITHUB_OUTPUT          
        elif [[ $prod_one_result == 'success' ]]  && [[ $prod_two_result == 'failure' ]] && [[ $prod_two_reviewed == 'true' ]]; then                    
           echo "slack_workflow_name=Build and Deploy - Prod2" >> $GITHUB_OUTPUT        
        elif [[ $prod_one_result == 'success' ]]  && [[ $prod_two_result == 'failure' ]] && [[ $prod_two_reviewed != 'true' ]]; then                       
           echo "slack_workflow_name=Build and Deploy - Prod2" >> $GITHUB_OUTPUT           
        else         
          echo "slack_workflow_name=Build and Deploy - Production" >> $GITHUB_OUTPUT 
        fi                               

  test_outputs:   
    needs: [set_success_fail_workflow_name]
    if: ${{ always() }}
    runs-on: ubuntu-latest  
    steps:
    - name: Print outputs
      env:
        prod_one_result: ${{ needs.set_success_fail_workflow_name.outputs.prod_one_result }}    
        prod_two_result: ${{ needs.set_success_fail_workflow_name.outputs.prod_two_result }}
  
      run: |
          echo "prod_one_result: $prod_one_result"
          echo "prod_two_result: $prod_two_result"
    
  slack_update_result_success_failure:    
    needs: [slack_update_pending_apr_prod_one, deploy-to-prod-one, slack_update_pending_apr_prod_two, deploy-to-prod-two, set_success_fail_workflow_name]
    # if: always()
    if: ${{ always() && success('slack_update_pending_apr_prod_one') }}    
    uses: ./.github/workflows/slack_result.yml
    with:
      SUCCESS_CHECK: ${{ needs.set_success_fail_workflow_name.outputs.prod_one_result  == 'success' && needs.set_success_fail_workflow_name.outputs.prod_two_result  == 'success' && 'true' || 'false' }}
      FAILURE_CHECK: ${{ (needs.set_success_fail_workflow_name.outputs.prod_one_result  == 'failure' && needs.deploy-to-prod-one.outputs.reviewed == 'true') || ( needs.set_success_fail_workflow_name.outputs.prod_two_result  == 'failure' && needs.deploy-to-prod-two.outputs.reviewed == 'true')  && 'true' || 'false' }}
      WORKFLOW_NAME: ${{ needs.set_success_fail_workflow_name.outputs.slack_workflow_name }}
      
  slack_update_result_cancelled:
    if: ${{ cancelled() || ( failure('deploy-to-prod-one')  &&  needs.deploy-to-prod-one.outputs.reviewed != 'true') || ( failure('deploy-to-prod-two')  &&  needs.deploy-to-prod-two.outputs.reviewed != 'true') }}    
    needs: [slack_update_pending_apr_prod_one, deploy-to-prod-one,slack_update_pending_apr_prod_two, deploy-to-prod-two, set_success_fail_workflow_name]
    uses: ./.github/workflows/slack_result.yml
    with:      
      SUCCESS_CHECK: 'false'
      FAILURE_CHECK: 'false'
      CANCELLED_CHECK: 'true'
      WORKFLOW_NAME: ${{ needs.set_success_fail_workflow_name.outputs.slack_workflow_name }}
    secrets: inherit
