name: Deploy to server
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      status:
        value: ${{ jobs.status-deploy.outputs.output1 }}

jobs: 
  wait_for_approval:    
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Deployment approved
      id: set-output
      run: |
        echo 'Deployment approved'
        echo "reviewed=true" >> $GITHUB_OUTPUT
        
  slack_update_in_progress:   
    needs: [wait_for_approval]
    uses: ./.github/workflows/slack_update.yml
    with:
      continue-on-error: true
    
  deploy-to-server:    
    environment: ${{ inputs.environment }}    
    runs-on: ubuntu-latest   
    steps:     
      - name: Run something
        run : |
          echo "Deploy to server" >> $GITHUB_STEP_SUMMARY
          # exit 1
                    
