name: Deploy to server
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string  
    outputs:
      status:
        value: ${{ jobs.status-deploy.outputs.output1 }}

jobs: 
  wait_for_approval:    
    runs-on: ubuntu-latest
    steps:
    - name: Deployment approved
      id: set-output
      run: |
        echo 'Deployment approved'
        echo "reviewed=true" >> $GITHUB_OUTPUT
        
  slack_update_in_progress:   
    needs: [wait_for_approval]
    uses: ./.github/workflows/slack_update.yml
    with:
      continue-on-error: true
    
  deploy-to-server:    
    environment: ${{ inputs.environment }}    
    runs-on: ubuntu-latest   
    steps:     
      - name: Run something
        run : |
          echo "Deploy to server" >> $GITHUB_STEP_SUMMARY
          # exit 1
                    
  status-deploy:
    runs-on: ubuntu-latest
    needs: deploy-to-server
    outputs:
      output1: ${{ steps.step1.outputs.status_deploy }}
    steps:
      - name: Status of the deploy to server
        id: step1
        run: echo "status_deploy=${{ needs.deploy-to-server.result }}" >> $GITHUB_OUTPUT
