name: Update Slack Post

on:
  workflow_call:
    inputs:
      continue-on-error:
        required: true
        type: boolean
        default: false
      
jobs:
  Slack_Update_Status:
    runs-on: ubuntu-latest
    # env:
    #   err: ${{ github.event.inputs.continue-on-error || 'latest' }}
    # continue-on-error: $err
    # continue-on-error: ${{ github.event.inputs.continue-on-error || false }} 
    # ${{github.event.inputs.username}} 
    continue-on-error: ${{ inputs.continue-on-error || false }} 
    steps:
      - name: Something
        run: |
          exit 1
          echo "Something"
