name: Update Slack Post

on:
  workflow_call:
      
jobs:
  Slack_Update_Status:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Something
        run: |
          exit 1
          echo "Someghing"
  # Slack-Status:
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs: Slack_Update_Status
  #   steps:
  #     - name: Status of the job
  #       run: |
  #         echo "slack_status=${{ needs.Slack_Update_Status.result }}" >> $GITHUB_OUTPUT
