name: Update Slack Post

on:
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        default: false
        required: true
      
jobs:
  Slack_Update_Status:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }} 
    steps:
      - name: Something
        run: |
          # exit 1
          echo "Something"
