name: Update Slack Post

on:
  workflow_call:
    # inputs:
    #   continue-on-error:
    #     required: true
    #     type: boolean  
      
jobs:
  Slack_Update_Status:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.continue-on-error }} 
    steps:
      - name: Something
        run: |
          exit 1
          echo "Something"
  # Slack-Status:
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs: Slack_Update_Status
  #   steps:
  #     - name: Status of the job
  #       run: |
  #         echo "slack_status=${{ needs.Slack_Update_Status.result }}" >> $GITHUB_OUTPUT
