name: Update Slack Post

on:
  workflow_call:
      
jobs:
  Slack_Update_Status:
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          exit 1
          echo "Someghing"



