name: Generate Workflow Result

on:
  workflow_call:        

jobs:
  Slack_Update_Status:
    runs-on:
      group: ADS
    steps:
      - name: Something
        run: |
          exit 1
          echo "Something"
